/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TrustAccessControl } from './TrustAccessControl.js';
export * as factories from './factories/index.js';
export { TrustAccessControl__factory } from './factories/TrustAccessControl__factory.js';